import { Dispatch, PropsWithChildren, SetStateAction, createContext, useEffect, useState } from "react"
import { ControlAnimation, setAnimationTime } from "../utils/controlAnimation"
import { IDefaultStyle, example_animations } from "../utils/exampleAnimations"
import { AnimationObj, checkAnimationJsonFormat } from "../utils/checkAnimationJsonFormat"

export type Animations = Record<string, Array<AnimationObj>>

export type Example_animations = keyof typeof example_animations | "custom"

interface IAnimationContext {
    html: string
    setHtml: Dispatch<SetStateAction<string>>
    css: string
    setCss: Dispatch<SetStateAction<string>>
    time: number
    setTime: Dispatch<SetStateAction<number>>
    currentTimePercentage: number
    setCurrentTimePercentage: Dispatch<SetStateAction<number>>
    play: boolean
    setPlay: Dispatch<SetStateAction<boolean>>
    animations: Animations
    setAnimations: Dispatch<SetStateAction<Animations>>
    openAddModal: boolean
    setOpenAddModal: Dispatch<SetStateAction<boolean>>
    animationType: AnimationType
    setAnimationType: Dispatch<SetStateAction<AnimationType>>
    defaultStyle: IDefaultStyle
    setDefaultStyle: Dispatch<SetStateAction<IDefaultStyle>>
    exampleAnimation: Example_animations
    setExampleAnimation: Dispatch<SetStateAction<Example_animations>>
    encodedAnimation: string
    setEncodedAnimation: Dispatch<SetStateAction<string>>
}

type PreGenerateAnimation = Record<string, Array<{ 
    propertie: string;
    value: string
}>>

type AnimationType = "ease" | "ease-in" | "ease-out" | "ease-in-out"

export const AnimationContext = createContext<IAnimationContext>({} as IAnimationContext)

export default function AnimationProvider({ children }: PropsWithChildren) {
    const [html, setHtml] = useState<string>(`<div class="element"></div>`)
    const [css, setCss] = useState<string>("")
    const [currentTimePercentage, setCurrentTimePercentage] = useState<number>(0)
    const [play, setPlay] = useState<boolean>(false)
    const [openAddModal, setOpenAddModal] = useState<boolean>(false)
    const [animationType, setAnimationType] = useState<AnimationType>("ease-in-out")
    
    const defaultExampleAnimation = example_animations.throw_and_fly
    const [exampleAnimation, setExampleAnimation] = useState<Example_animations>("throw_and_fly")
    const [time, setTime] = useState<number>(defaultExampleAnimation.time)
    const [defaultStyle, setDefaultStyle] = useState<IDefaultStyle>(defaultExampleAnimation.defaultStyle)
    const [animations, setAnimations] = useState<Animations>(defaultExampleAnimation.animation)
    const [encodedAnimation, setEncodedAnimation] = useState<string>(btoa(JSON.stringify(animations)))

    const insertCss = (cssString: string) => {
        try {
            const styleSheet = document.createElement('style');
            document.head.appendChild(styleSheet);
        
            // Validate the CSS before inserting
            if (styleSheet.sheet) {
                try {
                    styleSheet.sheet.insertRule(cssString, styleSheet.sheet.cssRules.length);
                } catch (error) {
                    console.error("Failed to parse CSS rule:", (error as { message: string }).message);
                    console.error("Offending CSS:", cssString);
                }
            } else {
                console.error("Failed to access stylesheet");
            }
        } catch (error) {
            console.error("Error creating stylesheet:", error);
        }
    }

    useEffect(() => {
        console.log("atualizou!", {
            exampleAnimation,
            time,
            defaultStyle,
        })
        const preGenerateAnimation: PreGenerateAnimation = {}

        Object.entries(animations).forEach(([propertie, keyframes]) => {
            keyframes.forEach(({ percentage, value }) => {
                preGenerateAnimation[percentage] = [
                    ...(preGenerateAnimation[percentage] ?? []),
                    {
                        propertie,
                        value
                    }
                ]
            })
        })

        const elementStyle = `
.element {
    ${defaultStyle.join(";\n\t")}${defaultStyle.length ? ";\n\t" : ""}animation: ${time}ms ${animationType} custom-animation infinite;
}`
        const keyframeString = `
@keyframes custom-animation {
${Object.entries(preGenerateAnimation).map(([percentage, properties]) => {
const values = properties.map(({ propertie, value }) => `${propertie}: ${value};`).join("\n\t\t")

return `\t${percentage}% {\n\t\t${values}\n\t}`;
}).join('\n')}
}
        `

        setCss(`/* Generated by css-animator */
${elementStyle}
${keyframeString}`)

        insertCss(keyframeString)
        insertCss(elementStyle)
    }, [animations, play, defaultStyle])

    useEffect(() => {
        const convertedTime = Math.fround(currentTimePercentage * time)
        const convertedTimeChecked = convertedTime > 0 ? convertedTime - 1 : convertedTime
        setAnimationTime(convertedTimeChecked)
    }, [currentTimePercentage])

    useEffect(() => {
        ControlAnimation("pause")
    }, [play])

    useEffect(() => {
        const selectedDefaultAnimation = example_animations[exampleAnimation];

        setTime(selectedDefaultAnimation.time)
        setDefaultStyle(selectedDefaultAnimation.defaultStyle)
        setAnimations(selectedDefaultAnimation.animation)
    }, [exampleAnimation])

    useEffect(() => {
        const timeout = setTimeout(() => {
            try {
                const decodeAnimation = JSON.parse(atob(encodedAnimation))
                const ifObjValid = checkAnimationJsonFormat(decodeAnimation)
                if (ifObjValid) {
                    setAnimations(decodeAnimation)
                    Object.entries(example_animations).forEach(([key, { animation: innerAnimation }]) => {
                        const encodingAnimation = btoa(JSON.stringify(innerAnimation))
                        if (encodingAnimation === encodedAnimation) {
                            setExampleAnimation(key as Example_animations)
                        }
                    })
                } else {
                    setExampleAnimation("custom")
                }
            } catch (error) {
                console.error(error)
                setExampleAnimation("custom")
            }
        }, 500);
        
        return () => clearTimeout(timeout)
    }, [encodedAnimation])

    useEffect(() => {
        const encodeAnimatios = btoa(JSON.stringify(animations))
        setEncodedAnimation(encodeAnimatios)
    }, [animations])

    return (
        <AnimationContext.Provider value={{
            html,
            setHtml,
            css,
            setCss,
            time,
            setTime,
            currentTimePercentage,
            setCurrentTimePercentage,
            play,
            setPlay,
            animations,
            setAnimations,
            openAddModal,
            setOpenAddModal,
            animationType,
            setAnimationType,
            defaultStyle,
            setDefaultStyle,
            exampleAnimation,
            setExampleAnimation,
            encodedAnimation,
            setEncodedAnimation,
        }}>
            {children}
        </AnimationContext.Provider>
    )
}
